# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LoveAnimationDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LoveAnimationDemo
  pod 'Masonry'
  pod 'SDWebImage', :git => 'https://github.com/rs/SDWebImage.git', :tag => '4.4.2'
end
